#!/bin/bash

cd .. # change to project dir
rm build/libs/sculk-*.jar || cd packs || exit
./gradlew build || cd packs || exit
cd packs || exit
mkdir -p "$1" || exit
cd "$1" || exit
shift 1
java -jar ../../build/libs/sculk-*.jar "$@" || cd .. || exit
cd ..
